 #                              Learning Pandas Chapter 3

In [3]:
import numpy as np

In [1]:
# a function that squares all the values
# in a sequence
def squares(values):
    
    result = []
    for v in values:
        result.append(v * v)  
    return result
# create 100,000 numbers using python range
to_square = range(100000)
# time how long it takes to repeatedly square them all
%timeit squares(to_square)

18.5 ms ± 613 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numpy as np
array_to_square = np.arange(0, 100000)
# and time using a vectorized operation
%timeit array_to_square ** 2

118 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
a1=np.array([1,2,3,4,5,6,7,8])

In [10]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
type(a1)

numpy.ndarray

In [14]:
np.size(a1)

8

In [15]:
# convert a python range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# numpy arange function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
# by default zeros datatype is float
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [26]:
np.linspace(0,10,100)

array([  0.        ,   0.1010101 ,   0.2020202 ,   0.3030303 ,
         0.4040404 ,   0.50505051,   0.60606061,   0.70707071,
         0.80808081,   0.90909091,   1.01010101,   1.11111111,
         1.21212121,   1.31313131,   1.41414141,   1.51515152,
         1.61616162,   1.71717172,   1.81818182,   1.91919192,
         2.02020202,   2.12121212,   2.22222222,   2.32323232,
         2.42424242,   2.52525253,   2.62626263,   2.72727273,
         2.82828283,   2.92929293,   3.03030303,   3.13131313,
         3.23232323,   3.33333333,   3.43434343,   3.53535354,
         3.63636364,   3.73737374,   3.83838384,   3.93939394,
         4.04040404,   4.14141414,   4.24242424,   4.34343434,
         4.44444444,   4.54545455,   4.64646465,   4.74747475,
         4.84848485,   4.94949495,   5.05050505,   5.15151515,
         5.25252525,   5.35353535,   5.45454545,   5.55555556,
         5.65656566,   5.75757576,   5.85858586,   5.95959596,
         6.06060606,   6.16161616,   6.26262626,   6.36

In [27]:
a1=np.arange(0,10)
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
a2 = np.arange(10, 20)

In [30]:
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
a1+a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [33]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
arr=np.arange(0,20).reshape(4,5)

In [39]:
arr[1,2]

7

In [37]:
arr[:1]

array([[0, 1, 2, 3, 4]])

In [38]:
arr[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
np.size(arr, 0)

4

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
np.size(arr, 1)

5

In [43]:
a = np.arange(5)
a < 2

array([ True,  True, False, False, False], dtype=bool)

In [44]:
a = np.arange(5)

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
(arr<2) | (arr>3)

array([[ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [5]:
a1 = np.arange(1, 10)

In [6]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1[3:8]

array([4, 5, 6, 7, 8])

In [49]:
a1[::2]

array([1, 3, 5, 7, 9])

In [50]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [6]:
import numpy as np
a1 = np.arange(0, 9)
# and reshape to a 3x3 2-d array
m = a1.reshape(3, 3)

In [7]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# reshaping in downward direction
reshaped = m.reshape(9)
reshaped

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
# Reshape changes the view of original matrix
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
raveled = m.ravel()
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# flattened is like ravel, but a copy of the data,
# not a view into the source
m2 = np.arange(0, 9).reshape(3,3)
flattened = m2.flatten()
# change in the flattened object
flattened[0] = 1000
flattened

array([1000,    1,    2,    3,    4,    5,    6,    7,    8])

In [19]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# we can reshape by assigning a tuple to the .shape property
# we start with this, which has one dimension
# The property can also be assigned a tuple, which will force the array to reshape itself as specified:
# and make it 3x3
flattened.shape = (3, 3)
# it is no longer flattened
flattened

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8]])

In [21]:
flattened.transpose()

array([[1000,    3,    6],
       [   1,    4,    7],
       [   2,    5,    8]])

# Combining Arrays 

In [24]:
a=np.arange(0,9).reshape(3,3)

In [26]:
b=np.arange(10,19).reshape(3,3)

In [29]:
# Horizontal Stack Horizontal stacking combines two arrays in a manner where the columns of the
# second array are placed to the right of those in the first array. The function actually
# stacks the two items provided in a two-element tuple.
np.hstack((a, b))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [30]:
# identical to concatenate along axis = 1
np.concatenate((a, b), axis = 1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [31]:
# vertical stack, adding b as rows after a's rows
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [32]:
# concatenate along axis=0 is the same as vstack
np.concatenate((a, b), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [33]:
# dstack stacks each independent column of a and b
np.dstack((a, b))

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])